---
title: "Optimization 3"
output: pdf_document
---

```{r}
library(dplyr)
cancer <- read.table("cancer.txt", header = TRUE, sep = "\t")
dev <- apply(cancer[, -1], 2, sd)
dev
```

```{r}
#Unscaled Data
data <- cancer[,-1]
data <- data %>% mutate_all(as.numeric)

c <- cov(data)
eig <- eigen(c)
evalue <- eig$values
evector <- eig$vectors
evector[,1:2]


#Coefficient indications the relation between PC and random variable
#Determine the first 5 Principle Components: Coeffecients (loadings) - reflect correlation between RV and PC 
```



```{r}
#Scaled Data

normal <- scale(data)
c <- cor(normal)
eig <- eigen(c)
evalue <- eig$values
evector <- eig$vectors

evector

#Standardize all RV - Use correlation matrix (Cov of a standardized RV)

#Comparing the unscaled loadings to the standard deviations, we can observe that for most variables, the loadings are smaller than their corresponding standard deviations. Concluding, that the loadings are not heavily weighted towards the largest standard deviations.
```


```{r}
farm <- read.csv("farmers.csv")
head(farm)

plot(farm$Family, farm$DistRD)
plot(farm$Family, farm$DistRD, ylim = c(0,40), xlim = c(0, 60))

plot(farm$DistRD, farm$Cattle)
plot(farm$DistRD, farm$Cattle, ylim = c(0,30), xlim = c(0, 40))

normal <- scale(farm)
c <- cor(normal)
eig <- eigen(c)
evalue <- eig$values
evector <- eig$vectors

evector[,1:5]

#The first principal component is a combination of all variables, as a majority are positive loadings. We can see that the rest of the loadings have a less of a relation between RV and PC. Other loadings, like 3 has a high correlation value, indicating a strong relation between that PC and RV. 
```



```{r}
g <- function(w) {
  return(sin(3 * w) + (1/3 * w)^2)
}

random_search1 <- function(g, alpha = 1, max_its = 100, n = 2, w0 = 0) {
  weight_history <- vector()
  cost_history <- vector()

  weight <- w0
  cost <- g(weight)

  weight_history <- c(weight_history, weight)
  cost_history <- c(cost_history, cost)

  if (alpha == "diminishing") {
    alpha <- 1
  } else {
    alpha <- alpha
  }
  
  
  for (i in 1:max_its) {
    for (j in 1:n) {
      direction <- runif(1, -1, 1)
      a <- weight + (alpha * direction)
      a <- g(a)
      if (cost > a){
        
      weight <- weight + (alpha * direction)
      cost <- g(weight)

      weight_history <- c(weight_history, weight)
      cost_history <- c(cost_history, cost)
      }
    }

   if (alpha == "diminishing") {
      alpha <- alpha / sqrt(i)
    }
  }
  
  
  list(weight_history = weight_history, cost_history = cost_history)
}

# Example usage
results <- random_search1(g, alpha = 0.1, max_its = 100, n = 2, w0 = -5)
results
#random_search1(g, alpha = 0.1, max_its = 100, n = 2, w0 = 2.5)

plot(results$weight_history , xlab = "Iteration", ylab = "Weight", main = "Weight History")

# Plot cost_history
plot(results$cost_history, xlab = "Iteration", ylab = "Cost", main = "Cost History")

  
```

```{r}
random_search <- function(g, a = "diminishing", max_its = 100, n = 1000, w0 = c(0, 0)) {
  weight_history <- list(w0)
  cost_history <- c(g(w0[1], w0[2]))
  
  if (a == "diminishing") {
    ap1 <- 1.0
  } else {
    ap1 <- a
  }
  
  for (i in 1:max_its) {
    directions <- matrix(rnorm(n * 2), ncol = 2)
    
    for (j in 1:n) {
      w <- weight_history[[length(weight_history)]]
      w_new <- w + ap1 * directions[j, ]
      cost <- g(w_new[1], w_new[2])
      
      if (cost < cost_history[length(cost_history)]) {
        weight_history <- c(weight_history, list(w_new))
        cost_history <- c(cost_history, cost)
      }
    }
    
    if (a == "diminishing") {
      ap1 <- ap1 / 2.0
    }
  }
  
  return(list(weight_history = do.call(rbind, weight_history), cost_history = cost_history))
}

g <- function(w1, w2) {
  return(100 * (w2 - w1^2)^2 + (1 - w1)^2)
}

result <- random_search(g, a = 1, max_its = 100, w0 = c(-3, -3))

# Plot cost history
plot(result$cost_history, xlab = "Iteration", ylab = "Cost", main = "Cost History")

```